## cinclude '<tamtypes.h>'
## cinclude '<debug.h>'
## cinclude '<sifrpc.h>'

local function SifInitRpc(mode : cint)  <cimport, nodecl> end
local function init_scr()  <cimport, nodecl> end
local function scr_printf(pat : cstring, ... : cvarargs) <cimport, nodecl> end

local function debug_print(fmt : string)
	print(fmt)
	scr_printf(fmt)
end

SifInitRpc(0)
init_scr()
debug_print("Testing from ".._VERSION.."!\n")
while true do end